export const slideData = [
    {
        cardImage: "/img/slider/slide1.png",
        leftOffer: "4 кв. 2023",
        leftOfferOther: "",
        rightOffer: "Эконом",
        title: "Оазис",
        location: "Октябрьский р-н",
        metroTitle: "Октябрьская — 10 мин.",
        appartSum: "324",
        area: "29,3",
        price: "2 500 000",
        company: "АКД-Мета",
  },
    {
      cardImage: "/img/slider/slide2.png",
      leftOffer: "4 кв. 2023",
      leftOfferOther: "",
      rightOffer: "Элит",
      title: "Цивилизация",
      location: "Калининский р-н",
      metroTitle: "",
      appartSum: "102",
      area: "28,5",
      price: "2 447 000",
      company: "СД строй",
  },
  {
    cardImage: "/img/slider/slide3.png",
    leftOffer: "Сдан",
    leftOfferOther: "",
    rightOffer: "Бизнес",
    title: "На Никитина",
    location: "Октябрьский р-н",
    metroTitle: "Речной вокзал — 14 мин.",
    appartSum: "122",
    area: "31,5",
    price: "3 700 000",
    company: "Брусника",
  },
  {
    cardImage: "/img/slider/slide4.png",
    leftOffer: "2-3 кв. 2022",
    leftOfferOther: "Есть сданные",
    rightOffer: "Комфорт",
    title: "Европейский берег",
    location: "Октябрьский р-н",
    metroTitle: "Речной вокзал — 20 мин.",
    appartSum: "240",
    area: "31,5",
    price: "2 700 000",
    company: "Сибакадемстрой",
  },
  ]